branches:
  only:
    - release
    - pre-release

environment:
  COLUMNS: 999
  GUILD_START_THRESHOLD: 0.5
  matrix:
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38-x64"

install:
  - "%PYTHON%\\python.exe -m pip install -U pip"
  - "%PYTHON%\\python.exe -m pip install -U setuptools"
  - "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install twine"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"
  - "%PYTHON%\\python.exe -m pip install pandas"

build: off

test_script:
  - "%PYTHON%\\python.exe setup.py bdist_wheel"
  - 'PowerShell -Command "%PYTHON%\\python.exe -m pip install dist\\$(ls dist)"'
  - "%PYTHON%\\Scripts\\guild check --offline -vT"

after_test:
  - "%PYTHON%\\python.exe -m twine upload --skip-existing dist\\*.whl"

artifacts:
  - path: dist\*

# Uncomment to enable post-mortem debugging over RDP:
##on_finish:
##  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
